import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {loadSources,reviewEvidence,validateEvidencePointer} from './core.mjs';import {templateNote,validateNote,unsupportedClaimFlags} from './notes.mjs';
const root=fileURLToPath(new URL('.',import.meta.url)),read=name=>JSON.parse(readFileSync(root+name,'utf8')),digest=data=>createHash('sha256').update(data).digest('hex'),write=(name,data)=>writeFileSync(root+name,JSON.stringify(data,null,2)+'\n',{flag:'wx'});
const cases=read('cases.json'),inventory=read('fixtures/original/inventory-fictional.json').records,sources=loadSources(),erratum=read('erratum.json');
const evidenceFor=c=>reviewEvidence({caseId:c.case_id,inventory:inventory.find(i=>i.inventory_id===c.inventory_id),advisoryId:c.advisory_id,admittedSources:c.admitted_sources,sources});
export function modelCase(c,evidence){return {case_id:c.case_id,question:c.question,inventory:inventory.find(i=>i.inventory_id===c.inventory_id),verified_evidence:{case_id:evidence.case_id,evidence_fingerprint:evidence.evidence_fingerprint,coverage_state:evidence.identity_or_coverage_state,vendor_statement:evidence.vendor_statement,running_state:evidence.running_state,facts:evidence.facts.map(f=>({...f,lookup_ids:f.lookup_ids??[]})),source_pointers:evidence.source_pointers,lookup_receipts:evidence.lookup_receipts,source_snapshot_hashes:evidence.source_snapshot_hashes,source_metadata:evidence.source_metadata,unknowns:evidence.unknowns,review_required:true},erratum:{id:erratum.id,interpretation:erratum.interpretation,E5Scope:erratum.E5Scope}};}
export function assessRecord(record,c,evidence,input,snapshot,inputBytes,snapshotBytes){let note=null,parse_state='unavailable';const issues=[];
 if(!record||typeof record!=='object'||Array.isArray(record))return {case_id:c.case_id,status:'invalid-artifact-schema',note:null,request_match:false,validation:{valid:false,issues:['Attempt must be an object.']},human_accepted:false,attempt:record};
 try{note=JSON.parse(record.raw?.message?.content);parse_state='valid-json';}catch{if(record.raw?.message?.content!==undefined)parse_state='invalid-json';}
 const expected=modelCase(c,evidence);let sent=null;try{sent=JSON.parse(record.request.messages.find(m=>m.role==='user').content);}catch{}
 const system=readFileSync(root+'model_client.py','utf8').match(/SYSTEM = '''([\s\S]*?)'''/)?.[1];const request=record.request;const request_match=JSON.stringify(sent)===JSON.stringify(expected)&&record.case_id===c.case_id&&record.sourceCommit===snapshot.sourceCommit&&record.modelInputDigest===digest(inputBytes)&&record.snapshotDigest===digest(snapshotBytes)&&request?.model==='qwen3:4b'&&request.messages?.length===2&&request.messages[0].role==='system'&&request.messages[0].content===system&&request.messages[1].role==='user'&&request.options?.num_ctx===4096&&request.options?.num_predict===640&&request.options?.temperature===0&&request.options?.seed===42&&request.stream===false&&request.think===false&&request.truncate===false&&request.shift===false;
 const validation=validateNote(note,evidence);if(!request_match)issues.push('request/source/snapshot identity mismatch');if(record.status!=='complete'||record.raw?.done!==true||record.raw?.done_reason==='length')issues.push('output incomplete');if(parse_state!=='valid-json')issues.push('note JSON invalid');
 const parts=Array.isArray(note?.explanations)?note.explanations:[],exact_fact_text_matches=parts.filter(p=>p&&evidence.facts.some(f=>f.id===p.fact_id&&f.text===p.text)).length;
 return {case_id:c.case_id,status:record.status,parse_state,request_match,note,validation:{...validation,valid:validation.valid&&!issues.length,issues:[...issues,...validation.issues]},rule_flagged_unsupported_claims:parts.flatMap(p=>unsupportedClaimFlags(p?.text,evidence.case_id)),exact_fact_text_matches,verified_fact_count:evidence.facts.length,semantic_support:'NOT_INDEPENDENTLY_ADJUDICATED',human_accepted:false,attempt:record};}
function main(){mkdirSync(root+'artifacts',{recursive:true});
 if(process.argv.includes('--prepare-reviewed-snapshot')){const input=read('artifacts/model-input.json'),expected={task:'Explain verified evidence; applicability is already determined by CPU rules. No raw model classification score.',developmentModelCalls:0,evaluationCaseCount:6,cases:cases.filter(c=>c.split==='evaluation').map(c=>modelCase(c,evidenceFor(c)))};if(JSON.stringify(input)!==JSON.stringify(expected))throw Error('Frozen input facts changed; preserve archive and stop');const names=['core.mjs','notes.mjs','cases.json','erratum.json','evaluate.mjs','model_client.py','fixtures/original/query-gold-v1.json','fixtures/original/inventory-fictional.json','fixtures/original/source-manifest.json','fixtures/original/vendor-data/ubuntu-cve-2024-6387.openvex.json','fixtures/original/vendor-data/ubuntu-usn-6859-1.openvex.json','fixtures/original/redhat-source-conflict-projection.json'];write('artifacts/source-snapshot-v2.json',{sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),originalGoldCommit:'7dfe946f800b3d80cd790dac956587bfc87d34ed',previousSnapshot:'source-snapshot.json',reason:'Pre-inference CPU archive/type/provenance validation fixes; same frozen input and original gold',erratum_id:erratum.id,modelInputDigest:digest(readFileSync(root+'artifacts/model-input.json')),sourceFileDigests:Object.fromEntries(names.map(name=>[name,digest(readFileSync(root+name))])),modelInput:input});return;}
 if(process.argv.includes('--baseline')){const gold=read('fixtures/original/query-gold-v1.json');const records=cases.map(c=>{const evidence=evidenceFor(c),expected=gold.cases.find(g=>g.case_id===c.case_id),note=templateNote(evidence);return {case_id:c.case_id,split:c.split,evidence,note,validation:validateNote(note,evidence),state_match:evidence.identity_or_coverage_state===expected.expected_identity_or_coverage_state,vendor_statement_match:evidence.vendor_statement===expected.expected_vendor_statement,pointers_valid:evidence.source_pointers.every(p=>validateEvidencePointer(p,{inventory:inventory.find(i=>i.inventory_id===c.inventory_id),sources})),erratum_applied:c.case_id==='E4'?erratum.id:null};});write('artifacts/baseline-executions.json',{kind:'actually executed CPU source rules and template; gold read only by evaluator',development_cases:3,evaluation_cases:6,model_calls:0,case_count:records.length,state_matches:records.filter(r=>r.state_match).length,vendor_statement_matches:records.filter(r=>r.vendor_statement_match).length,citation_bound_notes:records.filter(r=>r.validation.valid).length,formal_openvex_schema_validation:false,independent_security_adjudication:false,cases:records});return;}
 if(process.argv.includes('--prepare')){const input={task:'Explain verified evidence; applicability is already determined by CPU rules. No raw model classification score.',developmentModelCalls:0,evaluationCaseCount:6,cases:cases.filter(c=>c.split==='evaluation').map(c=>modelCase(c,evidenceFor(c)))};const text=JSON.stringify(input,null,2)+'\n';const names=['core.mjs','notes.mjs','cases.json','erratum.json','evaluate.mjs','model_client.py','fixtures/original/query-gold-v1.json','fixtures/original/inventory-fictional.json','fixtures/original/source-manifest.json','fixtures/original/vendor-data/ubuntu-cve-2024-6387.openvex.json','fixtures/original/vendor-data/ubuntu-usn-6859-1.openvex.json','fixtures/original/redhat-source-conflict-projection.json'];const snapshot={sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),originalGoldCommit:'7dfe946f800b3d80cd790dac956587bfc87d34ed',erratum_id:erratum.id,modelInputDigest:digest(text),sourceFileDigests:Object.fromEntries(names.map(name=>[name,digest(readFileSync(root+name))])),modelInput:input};writeFileSync(root+'artifacts/model-input.json',text,{flag:'wx'});write('artifacts/source-snapshot.json',snapshot);return;}
 const inputBytes=readFileSync(root+'artifacts/model-input.json'),snapshotBytes=readFileSync(root+'artifacts/source-snapshot-v2.json'),input=JSON.parse(inputBytes),snapshot=JSON.parse(snapshotBytes);if(digest(inputBytes)!==snapshot.modelInputDigest)throw Error('Input digest mismatch');for(const [name,sha]of Object.entries(snapshot.sourceFileDigests))if(digest(readFileSync(root+name))!==sha)throw Error('Frozen source changed '+name);const records=cases.filter(c=>c.split==='evaluation').map(c=>{const path=root+'artifacts/model-attempts/'+c.case_id+'.json';if(!existsSync(path))return {case_id:c.case_id,status:'not-attempted',note:null,human_accepted:false};let record;try{record=JSON.parse(readFileSync(path));}catch{return {case_id:c.case_id,status:'invalid-artifact-json',note:null,human_accepted:false};}return assessRecord(record,c,evidenceFor(c),input,snapshot,inputBytes,snapshotBytes);});write('artifacts/model-evaluation.json',{task:'Bound explanation of already verified facts; not independent applicability prediction',sourceCommit:snapshot.sourceCommit,originalGoldCommit:snapshot.originalGoldCommit,erratum_id:erratum.id,evaluation_denominator:6,development_calls:0,http_requests:records.filter(r=>r.attempt?.httpRequestAttempted).length,completed:records.filter(r=>r.attempt?.raw?.done===true&&r.attempt?.raw?.done_reason!=='length').length,citation_bound_notes:records.filter(r=>r.validation?.valid).length,raw_state_copies:records.filter(r=>r.note?.coverage_state===evidenceFor(cases.find(c=>c.case_id===r.case_id)).identity_or_coverage_state).length,semantic_support:'NOT_INDEPENDENTLY_ADJUDICATED',human_accepted_notes:0,additional_demo_calls:0,cases:records});
}
if(process.argv[1]===fileURLToPath(import.meta.url))main();
