import http from 'node:http';import {readFile,readFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';
import {loadSources,reviewEvidence,getPointer} from './core.mjs';import {templateNote,recordedNote,hash} from './notes.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));const readJson=name=>JSON.parse(readFileSync(root+name,'utf8'));
const cases=readJson('cases.json'),inventories=readJson('fixtures/original/inventory-fictional.json').records,erratum=readJson('erratum.json');
export function createDesk(){
 let sources=loadSources(),inventory=structuredClone(inventories),selected='D1',admissions=new Map(cases.map(c=>[c.case_id,[...c.admitted_sources]])),version=0,latestReceipt=null,history=[],method='template',modelEntries=[],modelError=null;
 try{modelEntries=readJson('artifacts/model-evaluation.json').cases;if(!Array.isArray(modelEntries))throw Error('invalid archive schema');}catch(error){modelEntries=[];if(error.code!=='ENOENT')modelError='Recorded model evaluation JSON/schema is invalid; raw file remains unchanged.';}
 const result=()=>{const c=cases.find(c=>c.case_id===selected);return reviewEvidence({caseId:c.case_id,inventory:inventory.find(i=>i.inventory_id===c.inventory_id),advisoryId:c.advisory_id,admittedSources:admissions.get(selected),sources});};
 const inspected=()=>{const evidence=result();return {evidence,note:method==='template'?{status:'DETERMINISTIC_TEMPLATE',note:templateNote(evidence),validation:null}:modelError?{status:'ARCHIVE_INVALID',note:null,validation:{valid:false,issues:[modelError]}}:recordedNote(modelEntries.find(e=>e?.case_id===selected),evidence)};};
 const inspectionHash=()=>{const {evidence,note}=inspected();return hash({evidence:evidence.evidence_fingerprint,erratum:hash(erratum),method,note:note.note?hash(note.note):null});};
 const compatibility=()=>({current:!!latestReceipt&&latestReceipt.inspection_fingerprint===inspectionHash(),reason:!latestReceipt?'No review receipt':latestReceipt.inspection_fingerprint===inspectionHash()?'Bound to this exact inventory, source set, snapshot and note.':'Historical review; inventory, admitted sources, snapshot, selected case or note changed. Fresh inspection required.'});
 const state=()=>{const {evidence,note}=inspected(),c=cases.find(c=>c.case_id===selected);return {version,selected,case:c,inventory:inventory.find(i=>i.inventory_id===c.inventory_id),evidence,note,method,inspection_fingerprint:inspectionHash(),erratum_id:erratum.id,rows:cases.map(row=>{const e=reviewEvidence({caseId:row.case_id,inventory:inventory.find(i=>i.inventory_id===row.inventory_id),advisoryId:row.advisory_id,admittedSources:admissions.get(row.case_id),sources});return {...row,state:e.identity_or_coverage_state,vendor_statement:e.vendor_statement};}),source_cards:sources.filter(s=>admissions.get(selected).includes(s.id)).map(s=>({id:s.id,hash:s.hash,metadata:s.metadata,simulation:s.simulation===true,pointers:evidence.source_pointers.filter(p=>p.source===s.id)})),source_options:sources.map(s=>({id:s.id,admitted:admissions.get(selected).includes(s.id)})),modified_admission:JSON.stringify(admissions.get(selected))!==JSON.stringify(c.admitted_sources),latest_receipt:latestReceipt,receipt_compatibility:compatibility(),history,model_calls_from_ui:0};};
 const mutate=(event)=>{version++;history.push({event,case_id:selected,version});};
 return http.createServer(async(req,res)=>{const json=(status,body)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body));};try{const url=new URL(req.url,'http://localhost'),path=url.pathname;
 if(req.method==='GET'&&path==='/api/state')return json(200,state());
 if(req.method==='GET'&&path==='/api/receipt'){if(!latestReceipt)return json(404,{error:'receipt_unavailable'});res.writeHead(200,{'Content-Type':'application/json','Content-Disposition':'attachment; filename="local-evidence-review.json"','Cache-Control':'no-store'});return res.end(JSON.stringify({receipt:latestReceipt,compatibility:compatibility()},null,2));}
 if(req.method==='GET'&&path==='/api/source'){const id=url.searchParams.get('id');if(!admissions.get(selected).includes(id))return json(403,{error:'source_not_admitted_for_current_inspection'});const s=sources.find(s=>s.id===id),pointer=url.searchParams.get('pointer')??'';if(!s)return json(404,{error:'source_unknown'});const value=pointer===''?s.document:getPointer(s.document,pointer);if(value===undefined)return json(404,{error:'pointer_missing'});return json(200,{source_id:id,snapshot_hash:s.hash,metadata:s.metadata,pointer,value,simulation:s.simulation===true});}
 if(req.method==='POST'&&path.startsWith('/api/')){if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`)return json(403,{error:'origin_rejected'});let body='';for await(const chunk of req){body+=chunk;if(body.length>20000)return json(413,{error:'body_limit'});}const input=JSON.parse(body||'{}');
 if(input.version!==version)return json(409,{error:'stale_inspection',message:'State changed. Inspect the current evidence before another decision.'});
 if(path==='/api/select'){if(!cases.some(c=>c.case_id===input.case_id))return json(400,{error:'case_unknown'});selected=input.case_id;method='template';mutate('selected_fixture');}
 else if(path==='/api/method'){if(!['template','model'].includes(input.method))return json(400,{error:'method_unknown'});method=input.method;mutate('selected_note_method');}
 else if(path==='/api/admission'){if(!Array.isArray(input.source_ids)||input.source_ids.some(id=>!sources.some(s=>s.id===id))||new Set(input.source_ids).size!==input.source_ids.length)return json(400,{error:'source_set_invalid'});admissions.set(selected,[...input.source_ids]);mutate('explicit_local_source_set_change');}
 else if(path==='/api/revise'){const s=sources.find(s=>s.id===input.source_id);if(!s||!admissions.get(selected).includes(s.id))return json(400,{error:'source_not_admitted'});s.document=structuredClone(s.document);s.document.demo_revision=(s.document.demo_revision??0)+1;s.hash=hash(s.document);s.metadata={...s.metadata,local_demo_revision:s.document.demo_revision};s.simulation=true;mutate('local_snapshot_revision_simulation');}
 else if(path==='/api/review'){const current=inspected();if(input.case_id!==selected||input.evidence_fingerprint!==current.evidence.evidence_fingerprint||input.inspection_fingerprint!==inspectionHash()||input.inventory_hash!==current.evidence.inventory_hash||JSON.stringify(input.source_snapshot_hashes)!==JSON.stringify(current.evidence.source_snapshot_hashes)||input.erratum_id!==erratum.id)return json(409,{error:'stale_review_binding',message:'Displayed identities or source facts changed. Fresh inspection required.'});if(input.confirm_evidence!==true)return json(400,{error:'inspection_confirmation_required'});if(method==='model'&&(!current.note.validation?.valid||input.confirm_semantics!==true))return json(400,{error:'model_note_not_reviewable',message:'A complete citation-bound explanation and separate semantic review are required.'});if(!latestReceipt||latestReceipt.inspection_fingerprint!==inspectionHash()){const receipt={id:randomUUID(),kind:'local_evidence_inspection_not_change_approval',case_id:selected,created_at:new Date().toISOString(),inspection_fingerprint:inspectionHash(),evidence:structuredClone(current.evidence),method,note:structuredClone(current.note.note),erratum_id:erratum.id,erratum_hash:hash(erratum),reviewer_assertion:'Evidence inspected; unknowns/conflicts retained. No real-machine safety or remediation approval.'};latestReceipt={...receipt,hash:hash(receipt)};mutate('evidence_review_recorded');}}
 else if(path==='/api/reset'){sources=loadSources();inventory=structuredClone(inventories);admissions=new Map(cases.map(c=>[c.case_id,[...c.admitted_sources]]));selected='D1';method='template';mutate('reset_original_fixtures');}
 else return json(404,{error:'action_unknown'});return json(200,state());}
 const files={'/':'index.html','/app.mjs':'app.mjs','/style.css':'style.css'};if(req.method!=='GET'||!files[path])return json(404,{error:'not_found'});readFile(root+files[path],(error,data)=>{if(error)return json(500,{error:'file_unavailable'});res.writeHead(200,{'Content-Type':path.endsWith('.mjs')?'text/javascript':path.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-store'});res.end(data);});
 }catch{return json(400,{error:'invalid_request'});}});
}
if(process.argv[1]===fileURLToPath(import.meta.url))createDesk().listen(5088,'127.0.0.1',()=>console.log('P08 local fictional evidence desk ready'));
